import type { ExecutionAnalysis, TransactionInput, WalletSignals } from "./types";
import { getChain } from "../chains";

const TRANSFER_TOPIC = "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a9df523b3ef";
const APPROVAL_TOPIC = "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925";
async function rpc<T>(url: string, method: string, params: unknown[]): Promise<T> { const response = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ jsonrpc: "2.0", id: Date.now(), method, params }), cache: "no-store" }); if (!response.ok) throw new Error(`RPC returned ${response.status}`); const payload = await response.json() as { result?: T; error?: { message: string } }; if (payload.error) throw new Error(payload.error.message); if (payload.result === undefined) throw new Error("RPC returned no result"); return payload.result; }

export async function inspectWallet(address: string, chainKey = "base", transaction?: TransactionInput): Promise<WalletSignals> {
  const chain = getChain(chainKey), token = chain.stablecoins[0];
  const [codeHex, balanceHex, transactionCountHex, tokenUnits, latestHex] = await Promise.all([rpc<string>(chain.rpcUrl, "eth_getCode", [address, "latest"]), rpc<string>(chain.rpcUrl, "eth_getBalance", [address, "latest"]), rpc<string>(chain.rpcUrl, "eth_getTransactionCount", [address, "latest"]), rpc<string>(chain.rpcUrl, "eth_call", [{ to: token.address, data: `0x70a08231000000000000000000000000${address.slice(2)}` }, "latest"]), rpc<string>(chain.rpcUrl, "eth_blockNumber", [])]);
  const walletType = codeHex === "0x" ? "eoa" : "contract", transactionCount = Number.parseInt(transactionCountHex, 16), latest = Number.parseInt(latestHex, 16), fromBlock = `0x${Math.max(0, latest - 100_000).toString(16)}`, pad = `0x${address.slice(2).padStart(64, "0")}`;
  let approvals: WalletSignals["approvals"] = [], transfers: WalletSignals["transfers"] = [];
  const limitations = [`History is limited to the most recent 100,000 ${chain.name} blocks.`, "Simulation is not configured; transaction analysis is based on current RPC state."];
  try { const [a, incoming, outgoing] = await Promise.all([rpc<any[]>(chain.rpcUrl, "eth_getLogs", [{ address: token.address, fromBlock, toBlock: "latest", topics: [APPROVAL_TOPIC, pad] }]), rpc<any[]>(chain.rpcUrl, "eth_getLogs", [{ address: token.address, fromBlock, toBlock: "latest", topics: [TRANSFER_TOPIC, null, pad] }]), rpc<any[]>(chain.rpcUrl, "eth_getLogs", [{ address: token.address, fromBlock, toBlock: "latest", topics: [TRANSFER_TOPIC, pad] }])]); approvals = a.map(log => ({ token: token.address, tokenLabel: token.symbol, owner: address, spender: `0x${log.topics[2].slice(-40)}`, amount: BigInt(log.data).toString(), blockNumber: Number.parseInt(log.blockNumber, 16) })); transfers = [...incoming, ...outgoing].map(log => ({ token: token.address, tokenLabel: token.symbol, from: `0x${log.topics[1].slice(-40)}`, to: `0x${log.topics[2].slice(-40)}`, amount: BigInt(log.data).toString(), blockNumber: Number.parseInt(log.blockNumber, 16), transactionHash: log.transactionHash })); } catch { limitations.push("Approval and transfer history could not be read from the configured RPC provider."); }
  const findings: WalletSignals["findings"] = [];
  if (walletType === "contract") findings.push({ id: "contract-wallet", severity: "low", title: "Contract wallet detected", description: "Transaction behavior may be governed by contract logic.", evidence: { codePrefix: codeHex.slice(0, 18) } });
  if (transactionCount === 0) findings.push({ id: "new-wallet", severity: "medium", title: "No outgoing transactions observed", description: "This address has no outgoing transaction count on the selected chain.", evidence: { transactionCount } });
  if (balanceHex === "0x0") findings.push({ id: "no-native-balance", severity: "medium", title: `No ${chain.nativeCurrency} balance`, description: `The wallet may be unable to pay fees on ${chain.name}.`, evidence: { nativeBalance: "0" } });
  if (approvals.some(a => BigInt(a.amount) > (1n << 128n))) findings.push({ id: "large-approval", severity: "high", title: `Large ${token.symbol} approval detected`, description: "The wallet has granted a very large allowance to a spender.", evidence: { token: token.address, count: approvals.length } });
  const execution = transaction ? await analyzeTransaction(chain.rpcUrl, transaction, balanceHex) : undefined;
  if (execution?.decodedCall?.amount && BigInt(execution.decodedCall.amount) > (1n << 128n)) findings.push({ id: "unlimited-approval-request", severity: "high", title: "Unlimited approval requested", description: "This call grants the spender access to all current and future tokens.", evidence: execution.decodedCall });
  return { address, chain, walletType, ethWei: BigInt(balanceHex).toString(), usdcBaseUnits: BigInt(tokenUnits).toString(), transactionCount, codeHex, approvals, transfers, labels: [{ address: token.address, label: `${token.symbol} (${chain.name})`, source: "configured chain token registry" }], sanctions: { checked: false, status: "unavailable" }, findings, limitations, execution };
}

async function analyzeTransaction(rpcUrl: string, tx: TransactionInput, balanceHex: string): Promise<ExecutionAnalysis> { const value = BigInt(tx.value || "0"), balance = BigInt(balanceHex), data = tx.data || ""; let gasPrice = 0n; try { gasPrice = BigInt(await rpc<string>(rpcUrl, "eth_gasPrice", [])); } catch { return { canPayGas: "unknown", canPayValue: balance >= value, simulationStatus: "not_run" }; } const gasCost = tx.gasLimit ? BigInt(tx.gasLimit) * gasPrice : 0n; const decodedCall = data.startsWith("0x095ea7b3") && data.length >= 138 ? { method: "approve(address,uint256)", token: tx.to, spender: `0x${data.slice(34, 74)}`, amount: BigInt(`0x${data.slice(74, 138)}`).toString() } : undefined; return { canPayGas: tx.gasLimit ? balance >= gasCost + value : "unknown", canPayValue: balance >= value, simulationStatus: "not_run", decodedCall }; }
